name: realtime_client
description: Listens to changes in a PostgreSQL Database and via websockets. This is for usage with Supabase Realtime server.
version: 0.0.8
homepage: "https://supabase.io"
repository: "https://github.com/supabase/realtime-dart"

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  lint: ^1.5.1
  mocktail: ^0.0.1-dev.11
  test: ^1.16.5
